<?php
/******************************************
US English
Admin Category Language
******************************************/

$lang['categories'] = 'Categorias';
$lang['error_must_select'] = 'Debes Seleccionar una Categoria para Organizar';
$lang['error_not_found'] = 'Categoria no Encontrada';
$lang['organize_category'] = 'Organizar "%s" Categoria';
$lang['organize'] = 'Organizar';
$lang['category_id'] = 'ID';
$lang['category_form'] = 'Formulario de Categoria';
$lang['name'] = 'Nombre';
$lang['slug'] = 'Slug';
$lang['hidden'] = 'Oculto';
$lang['description'] = 'Descripcion';
$lang['excerpt'] = 'Excerpt';
$lang['image'] = 'Imagen';
$lang['sequence'] = 'Sequence';
$lang['seo_title'] = 'SEO Title';
$lang['meta'] = 'Meta Data';
$lang['message_category_saved'] = 'La categoria se ha guardado!';
$lang['error_file_upload'] = '<p>No Seleccionaste una imagen para subir</p>'; //important. This must match the same error as generated by the file upload script of your language.
$lang['message_delete_category'] = 'La categoria se ha eliminado.';
$lang['current_file'] = 'Archivo Seleccionado';
$lang['confirm_delete_category'] = 'Estas seguro de que quieres eliminar la categoria?';
$lang['add_new_category'] = 'Agregar Nueva Categoria';
$lang['top_level_category'] = 'Categoria Principal';
$lang['no_categories'] = 'No Existen Categorias';
$lang['attributes'] = 'Atrobutos';
$lang['seo'] = 'SEO';
$lang['parent'] = 'Parentesco';
$lang['meta_data_description'] = 'ex. &lt;meta name="description" content="We sell products that help you" /&gt;';
$lang['drag_and_drop'] = 'Arrastra los productos en el orden que quieres que se muestren.';
$lang['sku'] = 'PID';
$lang['price'] = 'Precio';
$lang['sale'] = 'Precio de Venta';
$lang['max_file_size'] = 'Tamaño Maximo de Archivo';
$lang['sort_name_asc'] = 'Nombre (A - Z)';
$lang['sort_name_desc'] = 'Nombre (Z - A)';
$lang['sort_price_asc'] = 'Menor Precio';
$lang['sort_price_desc'] = 'Mayor Precio';
$lang['sort'] = 'Ordenar';
